# Native ARM64, self-contained CI image for the validated QEMU/GCC versions.
FROM ubuntu:16.04@sha256:f4c51ba054967fd4b06715f1b67078efbe9ca152e8be98d8f3c1f4d08c6042f8

ENV DEBIAN_FRONTEND=noninteractive
RUN test "$(dpkg --print-architecture)" = arm64 && \
    apt-get update && apt-get install -y --no-install-recommends \
    build-essential autoconf automake libtool bison flex curl ca-certificates \
    git patch genromfs python python3 pkg-config libncurses5-dev \
    libglib2.0-dev libpixman-1-dev zlib1g-dev bzip2 xz-utils file unzip && \
    rm -rf /var/lib/apt/lists/*

RUN curl --fail --location --retry 3 \
    https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-aarch64-linux.tar.bz2 \
    -o /tmp/gcc.tar.bz2 && \
    echo "f605b5f23ca898e9b8b665be208510a54a6e9fdd0fa5bfc9592002f6e7431208  /tmp/gcc.tar.bz2" | sha256sum -c - && \
    tar -xjf /tmp/gcc.tar.bz2 -C /opt && rm /tmp/gcc.tar.bz2
ENV PATH=/opt/gcc-arm-none-eabi-10.3-2021.10/bin:${PATH}

COPY 16m.patch /tmp/16m.patch
RUN curl --fail --location --retry 3 https://download.qemu.org/qemu-2.12.0.tar.xz \
    -o /tmp/qemu.tar.xz && \
    echo "e69301f361ff65bf5dabd8a19196aeaa5613c1b5ae1678f0823bdf50e7d5c6fc  /tmp/qemu.tar.xz" | sha256sum -c - && \
    mkdir -p /opt/qemu-src && tar -xJf /tmp/qemu.tar.xz -C /opt/qemu-src --strip-components=1 && \
    cd /opt/qemu-src && patch --fuzz=0 -p1 < /tmp/16m.patch && \
    ./configure --prefix=/opt/qemu-2.12.0-16m --target-list=arm-softmmu \
      --disable-werror --disable-gtk --disable-sdl --disable-vnc --disable-curses --disable-docs && \
    make -j4 && make install && \
    rm -rf /opt/qemu-src /tmp/qemu.tar.xz /tmp/16m.patch
ENV PATH=/opt/qemu-2.12.0-16m/bin:${PATH}
RUN arm-none-eabi-gcc --version && qemu-system-arm --version && python3 --version
WORKDIR /work/os
